apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app
  labels:
    app: zomato-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato-app
  template:
    metadata:
      labels:
        app: zomato-app
    spec:
      containers:
      - name: zomato
        image: harshalg01/zomato-app:latest
        ports:
        - containerPort: 3000
