apiVersion: v1
kind: Service
metadata:
  name: zomato-svc
  labels:
    app: zomato-app
spec:
  type: LoadBalancer
  selector:
    app: zomato-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
  
